/* tslint:disable */
import { vwIdCodeName } from './vw-id-code-name';
import { vwIdName } from './vw-id-name';
export interface vwBillingSettings  {
  billFrequencyDay?: null | number;
  billFrequencyDuration?: vwIdCodeName;
  billFrequencyMultidays?: null | string;
  billFrequencyNextDate?: null | string;
  billFrequencyQuantity?: null | number;
  billFrequencyRecursOn?: null | number;
  billFrequencyStartingDate?: null | string;
  billWhenHoliday?: null | number;
  changeNotes?: null | string;
  daysToPayInvoices?: null | number;
  effectiveBillFrequencyDay?: null | number;
  effectiveBillFrequencyDuration?: vwIdCodeName;
  effectiveBillFrequencyMultidays?: null | string;
  effectiveBillFrequencyNextDate?: null | string;
  effectiveBillFrequencyQuantity?: null | number;
  effectiveBillFrequencyRecursOn?: null | number;
  effectiveBillFrequencyStartingDate?: null | string;
  effectiveBillWhenHoliday?: null | number;
  effectiveIsInherited?: null | boolean;
  effectiveMonthlyRecursOn?: null | number;
  effectiveRepeatType?: null | number;
  fixedAmount?: null | number;
  fixedFeeAmountToPay?: null | number;
  fixedFeeBillOnWorkComplete?: null | boolean;
  fixedFeeDueDate?: null | string;
  fixedFeeIsFullAmount?: null | boolean;
  fixedFeeRemainingAmount?: null | number;
  id?: number;
  invoiceAddressId?: null | number;
  invoiceAddressUpdated?: null | boolean;
  invoiceDelivery?: vwIdCodeName;
  invoiceTemplateId?: null | number;
  isDisbursementIncluded?: null | boolean;
  isFixedAmount?: null | boolean;
  isInherited?: null | boolean;
  isTargetHour?: null | boolean;
  isWorkComplete?: null | boolean;
  matter?: vwIdName;
  minimumTrustBalance?: null | number;
  needToUpdateChildRecords?: boolean;
  office?: vwIdName;
  operatingAccountNumber?: null | string;
  operatingRoutingNumber?: null | string;
  paymentPlans?: null | boolean;
  person?: vwIdName;
  receiptTemplateId?: null | number;
  repeatType?: null | number;
  tenant?: vwIdName;
  timeDisplayFormat?: null | number;
  timeEntryGracePeriod?: null | number;
  timeEntryGracePeriodAt?: null | string;
  timeRoundingInterval?: null | number;
}
