/* tslint:disable */
import { vwAddCourt } from './vw-add-court';
import { vwAddress } from './vw-address';
import { vwAttorneyOffice } from './vw-attorney-office';
import { vwContactFormBuilder } from './vw-contact-form-builder';
import { vwCourt } from './vw-court';
import { vwIdCodeName } from './vw-id-code-name';
import { vwIdName } from './vw-id-name';
import { vwPersonPhone } from './vw-person-phone';
export interface vwClient  {
  addresses?: null | Array<vwAddress>;
  archiveReason?: null | string;
  billingAttorney?: vwIdName;
  changeStatusNotes?: null | string;
  commonName?: null | string;
  companyName?: null | string;
  consultAttorney?: vwIdName;
  consultationFeeRecordStatus?: vwIdName;
  consultationLawOffice?: vwIdName;
  corporateContacts?: null | Array<vwIdCodeName>;
  createdBy?: null | string;
  customUniqueNumber?: null | string;
  doNotContact?: null | boolean;
  doNotContactReason?: null | string;
  doNotContactReasonOther?: null | string;
  email?: null | string;
  firstName?: null | string;
  formerName?: null | string;
  gender?: null | string;
  groups?: null | Array<vwIdName>;
  id?: number;
  individualCompanyName?: null | string;
  initialConsultDate?: null | string;
  initialContactDate?: null | string;
  initialJurisdictionId?: null | number;
  invoicePreference?: vwIdName;
  isArchived?: boolean;
  isCompany?: null | boolean;
  isDraft?: null | boolean;
  isVisible?: boolean;
  jobTitle?: null | string;
  jurisdiction?: null | Array<vwIdCodeName>;
  jurisdictionCounty?: null | string;
  jurisdictionDetails?: vwCourt;
  jurisdictionDetailsToUpdate?: vwAddCourt;
  lastName?: null | string;
  maidenName?: null | string;
  marketingEmail?: null | boolean;
  marketingSMS?: null | boolean;
  matterId?: number;
  matterPractices?: vwIdName;
  matterStatus?: null | Array<vwIdName>;
  matterType?: null | Array<vwIdName>;
  middleName?: null | string;
  nextActionDate?: null | string;
  nextActionNote?: null | string;
  nickName?: null | string;
  notifyEmail?: null | boolean;
  notifySmS?: null | boolean;
  originatingAttorney?: vwIdName;
  password?: null | string;
  personFormBuilder?: vwContactFormBuilder;
  phones?: null | Array<vwPersonPhone>;
  practice?: null | string;
  preferredContactMethod?: null | string;
  primaryContactPerson?: vwIdCodeName;
  primaryOffice?: vwAttorneyOffice;
  referralMedium?: null | string;
  referralSource?: null | string;
  responsibleAttorneys?: null | Array<vwIdName>;
  retainDate?: null | string;
  role?: null | Array<vwIdName>;
  salutation?: null | string;
  secondaryOffices?: null | Array<vwIdName>;
  states?: null | Array<vwIdName>;
  suffix?: null | string;
  uniqueNumber?: null | number;
  userName?: null | string;
}
