/* tslint:disable */
import { EmployeeType } from './employee-type';
import { vwAttorneyOffice } from './vw-attorney-office';
import { vwIdName } from './vw-id-name';
import { vwPersonPhone } from './vw-person-phone';
export interface vwEmployee  {
  approvingManager?: vwIdName;
  commonName?: null | string;
  companyName?: null | string;
  doNotSchedule?: null | boolean;
  email?: null | string;
  employeeType?: EmployeeType;
  employmentEndDate?: null | string;
  employmentStartDate?: null | string;
  federalJurisdictions?: null | Array<vwIdName>;
  firstName?: null | string;
  fridayCloseHours?: null | string;
  fridayOpenHours?: null | string;
  groups?: null | Array<vwIdName>;
  id?: number;
  initialConsultPracticeAreas?: null | Array<vwIdName>;
  initialJurisdictionId?: null | number;
  isActivated?: boolean;
  isClientAssignment?: null | boolean;
  isCompany?: null | boolean;
  isDraft?: null | boolean;
  isInheritNotification?: null | boolean;
  isInitialConsultation?: null | boolean;
  isTenantAdmin?: null | boolean;
  isVisible?: boolean;
  jobFamily?: number;
  jobFamilyBaseRate?: null | number;
  jobFamilyIsCustom?: null | boolean;
  jobFamilyName?: null | string;
  jobTitle: null | string;
  lastLoggedIn?: null | string;
  lastName?: null | string;
  maidenName?: null | string;
  middleName?: null | string;
  mondayCloseHours?: null | string;
  mondayOpenHours?: null | string;
  nickName?: null | string;
  password?: null | string;
  phones?: null | Array<vwPersonPhone>;
  practiceManager?: vwIdName;
  preferredContactMethod?: null | string;
  primaryOffice?: vwAttorneyOffice;
  profilePicture?: null | string;
  reportingManager?: vwIdName;
  retainerPracticeAreas?: null | Array<vwIdName>;
  role?: null | Array<vwIdName>;
  salutation?: null | string;
  saturdayCloseHours?: null | string;
  saturdayOpenHours?: null | string;
  secondaryOffices?: null | Array<vwIdName>;
  states?: null | Array<vwIdName>;
  suffix?: null | string;
  sundayCloseHours?: null | string;
  sundayOpenHours?: null | string;
  thursdayCloseHours?: null | string;
  thursdayOpenHours?: null | string;
  tuesdayCloseHours?: null | string;
  tuesdayOpenHours?: null | string;
  userName?: null | string;
  wednesdayCloseHours?: null | string;
  wednesdayOpenHours?: null | string;
}
