/* tslint:disable */
import { WarnEventsOutOfOffice } from './warn-events-out-of-office';
import { vwClientAssociation } from './vw-client-association';
import { vwIdName } from './vw-id-name';
import { vwPersonPhone } from './vw-person-phone';
export interface vwFullPerson  {
  associatedWithClient?: null | boolean;
  associatedWithPC?: null | boolean;
  associationTypeId?: number;
  associationTypeName?: null | string;
  associations?: null | Array<vwIdName>;
  blockId?: null | number;
  clientAssociations?: null | Array<vwClientAssociation>;
  clientFlag?: null | string;
  clientId?: null | number;
  clientName?: null | string;
  clientNumber?: null | string;
  companyName?: null | string;
  customMatterNumber?: null | string;
  customUniqueNumber?: null | string;
  description?: null | string;
  doNotContact?: null | boolean;
  doNotContactReason?: null | string;
  doNotSchedule?: null | boolean;
  email?: null | string;
  empTimezone?: null | string;
  eventsOutOfOffice?: null | Array<WarnEventsOutOfOffice>;
  firstName?: null | string;
  fridayCloseHours?: null | string;
  fridayOpenHours?: null | string;
  id?: number;
  isCompany?: null | boolean;
  isDaylightSaving?: boolean;
  isEventVisibleToOther?: null | boolean;
  isVisible?: boolean;
  jobTitle?: null | string;
  lastName?: null | string;
  matterName?: null | string;
  matterNumber?: null | number;
  mondayCloseHours?: null | string;
  mondayOpenHours?: null | string;
  personPhoto?: null | string;
  personPhotoURL?: null | string;
  phones?: null | Array<vwPersonPhone>;
  preferredContactMethod?: null | string;
  preferredPhone?: null | string;
  primaryOffice?: vwIdName;
  primaryOfficeId?: number;
  primaryOfficeName?: null | string;
  priority?: number;
  responsibleAttorney?: null | string;
  role?: null | string;
  saturdayCloseHours?: null | string;
  saturdayOpenHours?: null | string;
  sundayCloseHours?: null | string;
  sundayOpenHours?: null | string;
  thursdayCloseHours?: null | string;
  thursdayOpenHours?: null | string;
  tmpClientNumber?: null | string;
  totalCount?: number;
  tuesdayCloseHours?: null | string;
  tuesdayOpenHours?: null | string;
  uniqueNumber?: null | number;
  wednesdayCloseHours?: null | string;
  wednesdayOpenHours?: null | string;
}
